### ISSUE TITLE
Example in README

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaIO/Parquet.jl#56]
I have quite a bit of trouble understanding  the below code. What is `Customer` and how is that defined?

```
julia> rc = RecCursor(p, 1:5, colnames(p), JuliaBuilder(p, Customer))
Record Cursor on /home/tan/Work/julia/packages/Parquet/test/parquet-compatibility/parquet-testdata/impala/1.1.1-SNAPPY/customer.impala.parquet
    rows: 1:5
    cols: c_acctbal.c_mktsegment.c_nationkey.c_name.c_address.c_custkey.c_phone.c_comment
```

**Comment by tanmaykm** [comment]
So here, `Customer` would be the name of the Julia struct type that you want your schema to be represented as. The struct will be generated dynamically.

This will likely change in [future](https://github.com/JuliaIO/Parquet.jl/pull/51#issuecomment-613763060) to use named tuples instead.

**Comment by xiaodaigh** [comment]
Let's close this when named tuples come in and we adjust this example. 

Also given, parquet is a columnar format, there is no example of reading a column?

**Comment by tanmaykm** [comment]
Yes, an example of reading a single column will be useful.

Parquet storage format is columnar, but it is also geared towards storing groups of columns that make sense together (`ColumnGroups`). And to make access faster, they are also chunked into `RowGroups`. That allows faster access to blocks of data, may or may not be a single column.

So reading a column group, instead of the full schema will also be useful.

**Comment by xiaodaigh** [comment]
We need a practical guide on how to read data. The example in the readme are quite incomprehensible and seems to be covering some complicated topic like JuliaBuilder (not even sure what it is).

I propose to organise it into practical components like
* What is a row group and how to read a rowgroup into a table e.g. DataFrames.jl?
* What is a column chunk/page. How to read a column? How to read a chunk?
* How to read the whole file and return a table e.g. DataFrame?

I can write some and reorganise it.
